DROP TABLE IF EXISTS Product;

CREATE TABLE Product (
    ProductID INTEGER PRIMARY KEY,
    ProductName TEXT,
    ProductDescription TEXT,
    ProductPrice INTEGER
);

INSERT INTO Product (ProductID, ProductName, ProductDescription, ProductPrice) VALUES
    (1, 'Laptop Pro X1', 'A powerful and sleek laptop designed for professionals. Features include a high-resolution display, fast processor, and all-day battery life', 435),
    (2, 'SmartHome Hub v2', 'The ultimate smart home automation hub. Connect and control your lights, thermostat, and security cameras seamlessly with this advanced device', 865),
    (3, 'ZenMaster Meditation Pillow', 'Find your zen with the ZenMaster Meditation Pillow. Made from eco-friendly materials, it provides the perfect support for your mindfulness practice', 742),
    (4, 'Velocity Fitness Tracker', 'Track your workouts and achieve your fitness goals with the Velocity Fitness Tracker. Monitor steps, calories, and sleep quality in style', 453),
    (5, 'Gourmet Coffee Sampler', 'Experience the finest coffee beans from around the world with our Gourmet Coffee Sampler. Each blend is carefully curated for a rich and unique flavor', 543),
    (6, 'SolarGlow Garden Lights', 'Illuminate your garden with SolarGlow Garden Lights. Powered by solar energy, these elegant lights add a warm and inviting glow to your outdoor space', 921),
    (7, 'Adventure Seeker Backpack', 'Embark on your next adventure with the Adventure Seeker Backpack. Durable, spacious, and equipped with multiple compartments for all your gear', 223),
    (8, 'Harmony Wireless Earbuds', 'Immerse yourself in crystal-clear audio with Harmony Wireless Earbuds', 336),
    (9, 'HarborView Relaxation Hammock Chair', 'Create your personal oasis with the HarborView Relaxation Hammock Chair. Perfect for indoor or outdoor use, it cradles you in comfort and style.', 335),
    (10, 'SpectraVR Virtual Reality Headset', 'Step into a new reality with the SpectraVR Virtual Reality Headset. Immerse yourself in breathtaking virtual worlds and experiences.', 783),
    (11, 'EcoClean Water Purification Bottle', 'Stay hydrated and healthy on-the-go with the EcoClean Water Purification Bottle. This innovative bottle filters water, removing impurities for clean and refreshing hydration.', 402),
    (12, 'Quantum Quasar Gaming Mouse', 'Gain the competitive edge with the Quantum Quasar Gaming Mouse. Designed for precision and speed, its the ultimate tool for gamers seeking victory.', 785),
    (13, 'Chefs Delight Knife set', 'Unleash your inner chef with the Chefs Delight Knife Set. Crafted from premium steel, these knives offer precision and durability for all your culinary adventures.', 135),
    (14, 'Lunar Glow Night Light Projector', 'Transform any room into a celestial wonderland with the Lunar Glow Night Light Projector. Relax under a mesmerizing display of stars and galaxies.', 1023),
    (15, 'Urban Commuter Electric Scooter', 'Navigate city streets with ease on the Urban Commuter Electric Scooter. Stylish, efficient, and eco-friendly, its the perfect ride for the modern commuter.', 95),
    (16, 'BioTech Plant Growth Accelerator', 'Boost plant growth and yield with the BioTech Plant Growth Accelerator. Harnessing advanced biotechnology, its a game-changer for avid gardeners and farmers.', 853),
    (17, 'AquaFit Swim Resistance Bands', 'Take your aquatic workouts to the next level with AquaFit Swim Resistance Bands. These bands provide resistance for a full-body workout in the pool.', 356),
    (18, 'Cosmic Harmony Bluetooth Speaker', 'Experience music in its full spectrum with the Cosmic Harmony Bluetooth Speaker. Its sleek design and powerful sound deliver an immersive audio experience.', 524),
    (19, 'Mystic Moonlight Aromatherapy Diffuser', 'Create a serene ambiance with the Mystic Moonlight Aromatherapy Diffuser. Enjoy the calming effects of essential oils as they disperse through the soft moonlit glow.', 997),
    (20, 'Quantum QuantumX 8K Action Camera', 'Capture lifes adventures in stunning detail with the Quantum QuantumX 8K Action Camera. Waterproof and durable, its built for every action-packed moment.', 125),
    (21, 'BioSculpt Fitness Body Sculptor', 'Achieve your fitness goals with the BioSculpt Fitness Body Sculptor. This cutting-edge device enhances muscle definition and aids in targeted fat loss.', 326),
    (22, 'Stellar Elegance Diamond Pendant', 'Radiate elegance with the Stellar Elegance Diamond Pendant. A timeless piece adorned with sparkling diamonds, it adds a touch of sophistication to any ensemble.', 687),
    (23, 'LunaSync Sleep Optimization Mask', 'Enhance your sleep quality with the LunaSync Sleep Optimization Mask. Utilizing advanced technology, it adjusts light exposure to align with your natural sleep-wake cycle.', 734),
    (24, 'NebulaVue Stargazing Telescope', 'Explore the wonders of the cosmos with the NebulaVue Stargazing Telescope. Its high-resolution optics bring distant galaxies and nebulae into sharp focus.',  231),
    (25, 'GreenThumb Smart Plant Sensor', 'Keep your plants thriving with the GreenThumb Smart Plant Sensor. Monitor soil moisture, sunlight, and nutrient levels, receiving real-time insights on your mobile device.', 295),
    (26, 'TruTaste Wine Aerator and Decanter', 'Elevate your wine-drinking experience with the TruTaste Wine Aerator and Decanter. Unleash the full flavor and aroma of your favorite wines in every sip.', 162),
    (27, 'NovaGlide Anti-Gravity Yoga Hammock', 'Experience yoga in a new dimension with the NovaGlide Anti-Gravity Yoga Hammock. Achieve deeper stretches and poses as you float in mid-air.', 173),
    (28, 'QuantumFlare Emergency Survival Kit', 'Be prepared for any situation with the QuantumFlare Emergency Survival Kit. Compact and comprehensive, it includes essentials for outdoor adventures and emergencies.', 2085),
    (29, 'AeroDash Pro Fitness Jump Rope', 'Take your cardio workouts to new heights with the AeroDash Pro Fitness Jump Rope. Designed for speed and precision, its a must-have for fitness enthusiasts.', 796),
    (30, 'Celestial Serenity Crystal Set', 'Harness positive energy with the Celestial Serenity Crystal Set. Each crystal is carefully selected for its unique properties, promoting balance and tranquility.', 641),
    (31, 'SolarSprint Portable Solar Charger', 'Stay charged on your outdoor adventures with the SolarSprint Portable Solar Charger. Harness the power of the sun to keep your devices ready for action.', 862),
    (32, 'BioHarmony Health Monitoring Bracelet', 'Monitor your health and wellness with the BioHarmony Health Monitoring Bracelet. It tracks vital signs and provides insights for a holistic approach to well-being.', 555),
    (33, 'SonicSculpt Ultrasonic Jewelry Cleaner', 'Restore the brilliance of your jewelry with the SonicSculpt Ultrasonic Jewelry Cleaner. Its advanced cleaning technology removes dirt and grime, bringing back the shine.', 432),
    (34, 'EcoPetal Sustainable Flower Seeds', 'Grow a garden that blooms sustainably with EcoPetal Sustainable Flower Seeds. These seeds are ethically sourced and cultivated to promote biodiversity.', 378),
    (35, 'QuantumSpark Creativity Booster', 'Ignite your creativity with the QuantumSpark Creativity Booster. Designed to stimulate inspiration, its a must-have for artists, writers, and innovators.', 3020);